version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Listing repo contents..."
      - ls -la .
      - ls -la src/main/java/ || echo "No Java sources found!"
      - ls -la src/main/webapp/ || echo "webapp directory missing!"
      - echo "Running Maven with debug..."
      - mvn clean package -X -Dmaven.test.skip=true  # Skip tests, enable debug
      - echo "Listing target/ contents..."
      - ls -la target/
      - cp target/nextwork-web-project.war . || echo "WAR file not found! Check src/main/webapp/ or Java sources."
      - cp appspec.yml . || echo "appspec.yml not found in root!"
  post_build:
    commands:
      - echo "Build complete!"
artifacts:
  files:
    - nextwork-web-project.war
    - appspec.yml
    - scripts/*
  discard-paths: no